### ISSUE TITLE
mAP 84.98%

### ISSUE THREAD

**Issue by beyza-yildirim** [csm-kr/yolo_v2_vgg16_pytorch#2]
Hello csm-kr,

Before jumping onto training myself, I wanted to validate the APs of your model with the weights you trained @ 149 epochs, and I've gotten a mAP of 84.98%, almost 8% more than what you've reported (https://github.com/csm-kr/yolo_v2_vgg16_pytorch#results):

88.76% = aeroplane AP 
89.35% = bicycle AP 
89.78% = bird AP 
82.10% = boat AP 
67.62% = bottle AP 
91.37% = bus AP 
89.10% = car AP 
93.65% = cat AP 
74.04% = chair AP 
90.92% = cow AP 
76.24% = diningtable AP 
91.78% = dog AP 
88.62% = horse AP 
88.21% = motorbike AP 
83.55% = person AP 
71.47% = pottedplant AP 
83.63% = sheep AP 
82.12% = sofa AP 
93.16% = train AP 
84.07% = tvmonitor AP 
mAP = 84.98%

It seemed too good to be true, so I decided to validate again, now only using 20% of the VOC2007 test dataset, which also seemed to perform really well:

93.15% = aeroplane AP 
89.79% = bicycle AP 
91.27% = bird AP 
86.96% = boat AP 
61.63% = bottle AP 
94.00% = bus AP 
91.09% = car AP 
92.06% = cat AP 
70.77% = chair AP 
94.03% = cow AP 
71.11% = diningtable AP 
88.57% = dog AP 
85.76% = horse AP 
89.96% = motorbike AP 
83.22% = person AP 
66.24% = pottedplant AP 
86.48% = sheep AP 
77.51% = sofa AP 
91.42% = train AP 
84.45% = tvmonitor AP 
mAP = 84.47%

**Comment by csm-kr** [comment]
@beyza-yildirim Hi~ beyza-yildirim
It seems strange that the mAP value is too high. 
I tested again, but i get the 77.03% as written in the repository.
it is suspicious that the conf threshold and the MINOVERLAP part of mAP.
please check if MINOVERLAP is 0.5
https://github.com/csm-kr/yolo_v2_vgg16_pytorch/blob/9d161c94df5521efcee3698c74b4ee872712ade6/voc_eval.py#L276
and the conf-thres is 0.01 at testing
https://github.com/csm-kr/yolo_v2_vgg16_pytorch/blob/9d161c94df5521efcee3698c74b4ee872712ade6/test.py#L140

**Comment by beyza-yildirim** [comment]
Hello @csm-kr, thank you for the reply, the problem is solved.
